apiVersion: batch/v1
kind: Job
metadata:
  name: seq-tag-ner-trainer
spec:
  parallelism: 4
  completions: 4
  template:
    metadata:
      labels:
        paddle-job: seq-tag-ner
    spec:
      imagePullSecrets:
        - name: job-registry-secret
      hostNetwork: true
      volumes:
        - name: nvidia-driver
          hostPath:
            path: /usr/local/nvidia/lib64
        - name: nvidia-smi
          hostPath:
            path: /usr/bin/nvidia-smi
      containers:
      - name: trainer
        #image: "registry.baidu.com/paddlepaddle/fluid_benchmark:gpu"
        image: "bootstrapper:5000/fluid_benchmark:gpu"
        imagePullPolicy: Always
        command: ["paddle_k8s", "start_fluid"]
        ports:
        - name: spread-50010
          containerPort: 50010
        volumeMounts:
          - mountPath: /usr/local/nvidia/lib64
            name: nvidia-driver
          - mountPath: /opt/bin/nvidia-smi
            name: nvidia-smi
        env:
        - name: PADDLE_JOB_NAME
          value: seq-tag-ner
        - name: TRAINING_ROLE
          value: "TRAINER"
        - name: TRAINERS
          value: "4"
        - name: PSERVERS
          value: "4"
        - name: TOPOLOGY
          value: ""
        - name: FLAGS_fraction_of_gpu_memory_to_use
          value: "0.4"
        - name: FLAGS_benchmark
          value: "1"
        #- name: GLOG_v
        #  value: "3"
        - name: GLOG_logtostderr
          value: "1"
        - name: MKL_NUM_THREADS
          value: "1"
        - name: LOCAL
          value: "FALSE"
        - name: BATCH_SIZE
          value: "50"
        - name: ENTRY
          value: "sleep 10 && unset http_proxy && unset https_proxy && cd /workspace/seq_tag_ner && python train.py"
        - name: TRAINER_PACKAGE
          value: "/workspace"
        - name: PADDLE_INIT_PORT
          value: "30258"
        - name: PADDLE_INIT_NICS
          value: "eth2"
        - name: PADDLE_INIT_TRAINER_COUNT
          value: "1"
        - name: PADDLE_INIT_PORTS_NUM
          value: "1"
        - name: PADDLE_INIT_PORTS_NUM_FOR_SPARSE
          value: "1"
        - name: PADDLE_INIT_NUM_GRADIENT_SERVERS
          value: "4"
        - name: LD_LIBRARY_PATH
          value: "/usr/local/nvidia/lib64:/usr/local/lib:/usr/local/cuda/lib64"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: "status.podIP"
        resources:
          requests:
            memory: 30Gi
            cpu: 2
          limits:
            memory: 30Gi
            cpu: 2
      restartPolicy: Never
